version: '3'
services:
  frontend:
    build: ./src/frontend
    ports: ["3000:3000"]
    networks:
      - custom_network
  backend:
    build: ./src/backend
    ports: ["3001:3001"]
    networks:
      - custom_network
    volumes:
    - ./data:/app/data
    - ./models:/app/models
    environment:
    - RUNNING_IN_DOCKER=1

networks:
  custom_network:
    driver: bridge
