version: '3'
services:
  frontend:
    build: ./src/frontend
    ports: ["3000:3000"]
    networks:
      - custom_network
  backend:
    build: ./src/backend
    ports: ["3001:3001"]
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
