version: '3'
services:
  frontend:
    build:
      context: ./src/frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3001

  backend:
    build:
      context: ./src/backend
    ports:
      - "3001:3001"
